export const LOADING_PRODUCTS = "LOADING PRODUCTS"
export const GET_PRODUCTS_S = "GET PRODUCTS SUCCESS"
export const GET_PRODUCTS_F = "GET PRODUCTS FAILED"

export const UP_PRODUCTS_S = "UPDATE PRODUCTS SUCCESS"
export const UP_PRODUCTS_F = "UPDATE PRODUCTS FAILED"
