export const LOADING_PRODUCTS = "LOADING PRODUCTS"
export const GET_PRODUCTS_S = "GET PRODUCTS SUCCESS"
export const GET_PRODUCTS_F = "GET PRODUCTS FAILED"

export const LOADING_UPDATE = "LOADING UPDATE"
export const UP_PRODUCTS_S = "UPDATE PRODUCTS SUCCESS"
export const UP_PRODUCTS_F = "UPDATE PRODUCTS FAILED"

export const ADD_PRODUCTS_S = "ADD PRODUCTS SUCCESS"
export const ADD_PRODUCTS_F = "ADD PRODUCTS FAILED"

export const DEL_PRODUCTS_S = "DEL PRODUCTS SUCCESS"
export const DEL_PRODUCTS_F = "DEL PRODUCTS FAILED"
